/**
 * @type {import('@remix-run/dev/config').AppConfig}
 */
module.exports = {
  ignoredRouteFiles: ["**/.*"],
  // When running locally in development mode, we use the built-in remix
  // server. This does not understand the vercel lambda module format,
  // so we default back to the standard build output.
  server: process.env.NODE_ENV === "development" ? undefined : "./server.ts",
  serverBuildPath: "api/index.js",
  // appDirectory: "app",
  // assetsBuildDirectory: "public/build",
  // publicPath: "/build/",
  future: {
    // TODO - enable these
    // v2_errorBoundary: true,
    // v2_headers: true,
    // v2_meta: true,
    // v2_normalizeFormMethod: true,
    // v2_routeConvention: true,
  },
  serverDependenciesToBundle: [
    // /^rehype.*/,
    // /^remark.*/,
    // /^unified.*/,
    // // custom
    // /^micromark.*/,
    // /^mdast.*/,
    // "decode-named-character-reference",
    // "character-entities",
    // "ccount",
    // /^unist.*/,
    // "markdown-table",
    // /^hast.*/,
    // "bail",
    // "trough",
    // "vfile",
    // "vfile-message",
    // "property-information",
    // "space-separated-tokens",
    // "comma-separated-tokens",
    // "vfile-location",
    // "web-namespaces",
    // "zwitch",
    // "html-void-elements",
    // "stringify-entities",
    // "character-entities-legacy",
    // "character-entities-html4",
    // "html-whitespace-sensitive-tag-names",
    // "is-absolute-url",
    // /^refractor.*/,
    // "parse-entities",
    // "character-reference-invalid",
    // "is-decimal",
    // "is-hexadecimal",
    // "is-alphanumerical",
    // "is-alphabetical",
    // "is-plain-obj",
    // "trim-lines",
    "mdx-bundler",
    // "github-slugger",
    // "escape-string-regexp",
  ],
};
