/** @type {import('@remix-run/dev').AppConfig} */
module.exports = {
  ignoredRouteFiles: ["**/.*"],
  serverModuleFormat: "cjs",
  serverDependenciesToBundle: [
    /^rehype.*/,
    /^remark.*/,
    /^unified.*/,
    /^mdast.*/,
    /^unist.*/,
    /^hast.*/,
    /^vfile.*/,
    /^micromark.*/,
    /^markdown.*/,
    /^html.*/,
    /^character.*/,
    /^refractor.*/,
    /^parse.*/,
    /^mdx.*/,
    /^is.*/,
    "github-slugger",
    "space-separated-tokens",
    "bail",
    "trough",
    "ccount",
    "property-information",
    "web-namespaces",
    "zwitch",
    "fault",
    "decode-named-character-reference",
    "escape-string-regexp",
    "comma-separated-tokens",
    "stringify-entities",
    "trim-lines",
    "estree-util-is-identifier-name",
    "@ungap/structured-clone",
    "devlop",
    "longest-streak",
  ],
};
