/**
 * @type {import('@remix-run/dev/config').AppConfig}
 */
module.exports = {
  // appDirectory: "app",
  // assetsBuildDirectory: "public/build",
  // publicPath: "/build/",
  // serverBuildDirectory: "api/_build",
  server: process.env.NODE_ENV === "development" ? undefined : "./server.js",
  ignoredRouteFiles: ["**/.*"],
  serverBuildTarget: "vercel",
  serverDependenciesToBundle: [
    /^rehype.*/,
    /^remark.*/,
    /^unified.*/,
    // custom
    /^micromark.*/,
    /^mdast.*/,
    "decode-named-character-reference",
    "character-entities",
    "ccount",
    /^unist.*/,
    "markdown-table",
    /^hast.*/,
    "bail",
    "trough",
    "vfile",
    "vfile-message",
    "property-information",
    "space-separated-tokens",
    "comma-separated-tokens",
    "vfile-location",
    "web-namespaces",
    "zwitch",
    "html-void-elements",
    "stringify-entities",
    "character-entities-legacy",
    "character-entities-html4",
    "html-whitespace-sensitive-tag-names",
    "is-absolute-url",
    /^refractor.*/,
    "parse-entities",
    "character-reference-invalid",
    "is-decimal",
    "is-hexadecimal",
    "is-alphanumerical",
    "is-alphabetical",
    "is-plain-obj",
    "trim-lines",
  ],
};
